name: Linux Build (GCC)
on:
  pull_request:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/integration-linux-build-gcc.yml'
    - '**/Makefile'
    - 'src/**.c'
    - 'src/**.h'
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build for Auriga
      run: make -j "$(nproc)"
